# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59c43521f7c82fdeeea3af3dd51e9b738c92de6ff0fe35b82903df48dfe67de3bdc3e002003e4dbde836cb0c75a75a4ccae24b03d17358ffdd30ceea2bd82f72

test:
  secret_key_base: 9641cc7b7216cae1df1652751a51acad3caa48c5b1032167760523852e419ed5776f0a2a31191ae491f8e201e7ad679edca680656c8ee219b8642f9e7fe009ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
